local Pokecenters = {
    -- kanto
    "Pokecenter Celadon",
    "Pokecenter Cerulean",
    "Pokecenter Cinnabar",
    "Pokecenter Fuchsia",
    "Pokecenter Lavender",
    "Pokecenter Route 10",
    "Pokecenter Route 3",
    "Pokecenter Saffron",
    "Pokecenter Vermilion",
    "Pokecenter Viridian",
    "Pokecenter Pewter",
    "Mt. Silver Pokecenter",
    "Indigo Plateau Center Johto",
    "Indigo Plateau Center",
    "Pokecenter Love Island",
    "Pokecenter Trainers Valley",
    -- Johto
    "Olivine Pokecenter",
    "Pokecenter Azalea",
    "Pokecenter Blackthorn",
    "Pokecenter Cherrygrove City",
    "Pokecenter Cianwood",
    "Pokecenter Ecruteak",
    "Pokecenter Goldenrod",
    "Pokecenter Mahogany",
    "Pokecenter Route 32",
    "Pokecenter Route 48",
    "Pokecenter Violet City",
    -- Hoen
    "Pokecenter Dewford Town",
    "Pokecenter Ever Grande City",
    "Pokecenter Fallarbor Town",
    "Pokecenter Fortree City",
    "Pokecenter Lavaridge Town",
    "Pokecenter Lilycove City",
    "Pokecenter Mauville City",
    "Pokecenter Mossdeep City",
    "Pokecenter Oldale Town",
    "Pokecenter Pacifidlog Town",
    "Pokecenter Petalburg City",
    "Pokecenter Rustboro City",
    "Pokecenter Slateport",
    "Pokecenter Sootopolis City",
    "Pokecenter Verdanturf",
    "Pokemon League Hoenn",
    "Pokecenter Eastern Peak",
    "Pokecenter Western Peak",
    "Pokecenter Leev Town",
    -- Sevii Islands
    "Pokecenter One Island",
    "Pokecenter Two Island",
    "Pokecenter Three Island",
    "Pokecenter Four Island",
    "Pokecenter Five Island",
    "Pokecenter Six Island",
    "Pokecenter Seven Island",
    -- Event
    "Pokecenter Vulcanic Town",
	"Pokecenter Cryofrost Town",
}

return Pokecenters
